<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CareerPathway extends Model
{
    use HasFactory;

    protected $fillable = [
        'slug',
        'title',
        'badge',
        'color',
        'icon',
        'description',
        'skills',
        'duration',
        'level',
        'price',
        'curriculum_modules',
        'sort_order',
        'is_active',
        'is_locked',
    ];

    protected $casts = [
        'skills' => 'array',
        'curriculum_modules' => 'array',
        'is_active' => 'boolean',
        'is_locked' => 'boolean',
        'price' => 'integer',
        'sort_order' => 'integer',
    ];

    /**
     * Curriculum media backed by ContentItem must persist the stable item ID,
     * never a temporary signed stream URL. Signed URLs are transport data and
     * are regenerated by CareerPathwayController when the pathway is read.
     *
     * The normalizer also accepts the legacy payload shape where only a
     * /api/stream/{id} URL was sent, so older admin clients are upgraded
     * automatically instead of reintroducing expiring URLs into the DB.
     */
    public function setCurriculumModulesAttribute($value): void
    {
        if (is_string($value)) {
            $decoded = json_decode($value, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $value = $decoded;
            }
        }

        if (is_array($value)) {
            $value = $this->normalizeCurriculumModules($value);
        }

        $this->attributes['curriculum_modules'] = $value === null
            ? null
            : json_encode($value, JSON_UNESCAPED_SLASHES);
    }

    private function normalizeCurriculumModules(array $modules): array
    {
        foreach ($modules as $moduleIndex => $module) {
            if (!is_array($module)) {
                continue;
            }

            foreach (['documents', 'videos'] as $collection) {
                if (empty($module[$collection]) || !is_array($module[$collection])) {
                    continue;
                }

                foreach ($module[$collection] as $itemIndex => $media) {
                    if (!is_array($media)) {
                        continue;
                    }

                    $contentItemId = $media['content_item_id'] ?? null;
                    if (is_numeric($contentItemId) && (int) $contentItemId > 0) {
                        $media['content_item_id'] = (int) $contentItemId;
                    } else {
                        $contentItemId = null;
                    }

                    if (!$contentItemId) {
                        foreach (['file_url', 'video_url'] as $urlKey) {
                            if (!empty($media[$urlKey])
                                && preg_match('#/api/stream/(\d+)#', (string) $media[$urlKey], $matches)
                            ) {
                                $contentItemId = (int) $matches[1];
                                break;
                            }
                        }
                    }

                    if ($contentItemId) {
                        $media['content_item_id'] = $contentItemId;
                        unset($media['file_url'], $media['video_url']);
                    }

                    $thumbnailContentItemId = $media['thumbnail_content_item_id'] ?? null;
                    if (is_numeric($thumbnailContentItemId) && (int) $thumbnailContentItemId > 0) {
                        $thumbnailContentItemId = (int) $thumbnailContentItemId;
                        $media['thumbnail_content_item_id'] = $thumbnailContentItemId;
                    } else {
                        $thumbnailContentItemId = null;
                    }

                    if (!$thumbnailContentItemId && !empty($media['thumbnail_url'])
                        && preg_match('#/api/stream/(\d+)#', (string) $media['thumbnail_url'], $matches)
                    ) {
                        $thumbnailContentItemId = (int) $matches[1];
                        $media['thumbnail_content_item_id'] = $thumbnailContentItemId;
                    }

                    if ($thumbnailContentItemId) {
                        unset($media['thumbnail_url']);
                    }

                    $modules[$moduleIndex][$collection][$itemIndex] = $media;
                }
            }
        }

        return $modules;
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}
