<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CareerPathway extends Model
{
    use HasFactory;

    protected $fillable = [
        'slug',
        'title',
        'badge',
        'color',
        'icon',
        'description',
        'skills',
        'duration',
        'level',
        'price',
        'curriculum_modules',
        'sort_order',
        'is_active',
        'is_locked',
    ];

    protected $casts = [
        'skills' => 'array',
        'curriculum_modules' => 'array',
        'is_active' => 'boolean',
        'is_locked' => 'boolean',
        'price' => 'integer',
        'sort_order' => 'integer',
    ];

    /**
     * Curriculum documents backed by ContentItem must persist the stable item
     * ID, never a temporary signed stream URL. Signed URLs are transport data
     * and are regenerated by CareerPathwayController when the pathway is read.
     *
     * The normalizer accepts both the current payload shape (content_item_id)
     * and the legacy payload shape where only a /api/stream/{id} URL was sent.
     * It also repairs old seeded placeholder-PDF links when an uploaded
     * ContentItem with the same document title exists.
     */
    public function setCurriculumModulesAttribute($value): void
    {
        if (is_string($value)) {
            $decoded = json_decode($value, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                $value = $decoded;
            }
        }

        if (is_array($value)) {
            $value = $this->normalizeCurriculumModules($value);
        }

        $this->attributes['curriculum_modules'] = $value === null
            ? null
            : json_encode($value, JSON_UNESCAPED_SLASHES);
    }

    private function normalizeCurriculumModules(array $modules): array
    {
        foreach ($modules as $moduleIndex => $module) {
            if (!is_array($module)) {
                continue;
            }

            if (empty($module['documents']) || !is_array($module['documents'])) {
                continue;
            }

            foreach ($module['documents'] as $documentIndex => $document) {
                if (!is_array($document)) {
                    continue;
                }

                $contentItemId = $document['content_item_id'] ?? null;
                if (is_numeric($contentItemId) && (int) $contentItemId > 0) {
                    $contentItemId = (int) $contentItemId;
                } else {
                    $contentItemId = null;
                }

                // Backward compatibility: older admin clients submitted the
                // freshly-signed URL returned by POST /api/admin/items.
                if (!$contentItemId && !empty($document['file_url'])
                    && preg_match('#/api/stream/(\d+)#', (string) $document['file_url'], $matches)
                ) {
                    $contentItemId = (int) $matches[1];
                }

                // Repair legacy seeded placeholder PDFs. The admin upload flow
                // creates the ContentItem immediately before saving the pathway,
                // so an exact title match is deterministic and lets the public
                // controller replace the placeholder with a fresh signed URL.
                $fileUrl = (string) ($document['file_url'] ?? '');
                $isLegacyPlaceholder = str_contains($fileUrl, 'raw.githubusercontent.com/mozilla/pdf.js/')
                    && str_contains($fileUrl, 'compressed.tracemonkey-pldi-09.pdf');

                if (!$contentItemId && $isLegacyPlaceholder && !empty($document['title'])) {
                    $contentItemId = ContentItem::query()
                        ->where('section', 'lecture_material')
                        ->where('title', (string) $document['title'])
                        ->whereNotNull('file_path')
                        ->latest('id')
                        ->value('id');
                }

                if ($contentItemId) {
                    $document['content_item_id'] = $contentItemId;
                    unset($document['file_url']);
                }

                $modules[$moduleIndex]['documents'][$documentIndex] = $document;
            }
        }

        return $modules;
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}
